apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "game-2048.deploymentName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "game-2048.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "game-2048.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80