apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-2048.serviceName" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "game-2048.selectorLabels" . | nindent 4 }}